services:
    auth-service:
        build:
            context: .
            dockerfile: Dockerfile.auth-service
        ports:
            - "8000:5000"
        depends_on:
            - postgres
            - redis
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - AUTH_SERVER=voidwalker-postgres-1
            - AUTH_USER=postgres
            - AUTH_PASSWORD=password
            - AUTH_PORT=5432
        links:
            - redis
            - postgres
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    postgres:
        image: "postgres:alpine"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"
